const movieCatalog = [
  {
    id: "m1",
    title: "Oppenheimer",
    genres: ["Drama", "History", "Biography"],
    director: "Christopher Nolan",
    actors: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    language: "English",
    year: 2023,
    rating: 8.9,
    runtime: 180,
    streaming: "Peacock",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb."
  },
  {
    id: "m2",
    title: "Dune: Part Two",
    genres: ["Sci-Fi", "Adventure", "Action"],
    director: "Denis Villeneuve",
    actors: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    language: "English",
    year: 2024,
    rating: 8.8,
    runtime: 166,
    streaming: "Max",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family."
  },
  {
    id: "m3",
    title: "Interstellar",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    director: "Christopher Nolan",
    actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    language: "English",
    year: 2014,
    rating: 8.7,
    runtime: 169,
    streaming: "Paramount+",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."
  },
  {
    id: "m4",
    title: "Inception",
    genres: ["Sci-Fi", "Action", "Thriller"],
    director: "Christopher Nolan",
    actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    language: "English",
    year: 2010,
    rating: 8.8,
    runtime: 148,
    streaming: "Netflix",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea."
  },
  {
    id: "m5",
    title: "Spirited Away",
    genres: ["Anime", "Fantasy", "Adventure"],
    director: "Hayao Miyazaki",
    actors: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    language: "Japanese",
    year: 2001,
    rating: 8.6,
    runtime: 125,
    streaming: "Max",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits."
  },
  {
    id: "m6",
    title: "The Dark Knight",
    genres: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    language: "English",
    year: 2008,
    rating: 9.0,
    runtime: 152,
    streaming: "Max",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests."
  },
  {
    id: "m7",
    title: "Everything Everywhere All at Once",
    genres: ["Sci-Fi", "Adventure", "Comedy"],
    director: "Daniel Kwan",
    actors: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
    language: "English",
    year: 2022,
    rating: 8.5,
    runtime: 139,
    streaming: "Netflix",
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes."
  },
  {
    id: "m8",
    title: "Parasite",
    genres: ["Thriller", "Drama", "Comedy"],
    director: "Bong Joon Ho",
    actors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    language: "Korean",
    year: 2019,
    rating: 8.5,
    runtime: 132,
    streaming: "Max",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan."
  },
  {
    id: "m9",
    title: "Knives Out",
    genres: ["Comedy", "Mystery", "Thriller"],
    director: "Rian Johnson",
    actors: ["Daniel Craig", "Chris Evans", "Ana de Armas"],
    language: "English",
    year: 2019,
    rating: 7.9,
    runtime: 130,
    streaming: "Netflix",
    description: "A detective investigates the death of the patriarch of an eccentric, combative family."
  },
  {
    id: "m10",
    title: "Spider-Man: Across the Spider-Verse",
    genres: ["Action", "Adventure", "Animation"],
    director: "Joaquim Dos Santos",
    actors: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"],
    language: "English",
    year: 2023,
    rating: 8.6,
    runtime: 140,
    streaming: "Netflix",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence."
  },
  {
    id: "m11",
    title: "Whiplash",
    genres: ["Drama", "Music"],
    director: "Damien Chazelle",
    actors: ["Miles Teller", "J.K. Simmons", "Paul Reiser"],
    language: "English",
    year: 2014,
    rating: 8.5,
    runtime: 106,
    streaming: "Netflix",
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing."
  },
  {
    id: "m12",
    title: "Get Out",
    genres: ["Horror", "Mystery", "Thriller"],
    director: "Jordan Peele",
    actors: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    language: "English",
    year: 2017,
    rating: 7.8,
    runtime: 104,
    streaming: "Peacock",
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception reaches a boiling point."
  },
  {
    id: "m13",
    title: "La La Land",
    genres: ["Romance", "Comedy", "Drama", "Music"],
    director: "Damien Chazelle",
    actors: ["Ryan Gosling", "Emma Stone", "Rosemarie DeWitt"],
    language: "English",
    year: 2016,
    rating: 8.0,
    runtime: 128,
    streaming: "Netflix",
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations."
  },
  {
    id: "m14",
    title: "The Godfather",
    genres: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    language: "English",
    year: 1972,
    rating: 9.2,
    runtime: 175,
    streaming: "Paramount+",
    description: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son."
  },
  {
    id: "m15",
    title: "Pulp Fiction",
    genres: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    actors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    language: "English",
    year: 1994,
    rating: 8.9,
    runtime: 154,
    streaming: "Max",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption."
  },
  {
    id: "m16",
    title: "Blade Runner 2049",
    genres: ["Sci-Fi", "Action", "Drama"],
    director: "Denis Villeneuve",
    actors: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    language: "English",
    year: 2017,
    rating: 8.0,
    runtime: 164,
    streaming: "Max",
    description: "A new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos."
  },
  {
    id: "m17",
    title: "Poor Things",
    genres: ["Comedy", "Romance", "Sci-Fi"],
    director: "Yorgos Lanthimos",
    actors: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe"],
    language: "English",
    year: 2023,
    rating: 8.0,
    runtime: 141,
    streaming: "Hulu",
    description: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist."
  },
  {
    id: "m18",
    title: "Perfect Blue",
    genres: ["Anime", "Thriller", "Horror"],
    director: "Satoshi Kon",
    actors: ["Junko Iwao", "Rica Matsumoto", "Shinpachi Tsuji"],
    language: "Japanese",
    year: 1997,
    rating: 8.0,
    runtime: 81,
    streaming: "Prime Video",
    description: "A retired pop singer turned actress's sense of reality starts to slip when she is stalked by an obsessed fan and plagued by ghosts of her past."
  },
  {
    id: "m19",
    title: "Kimi no Na wa (Your Name.)",
    genres: ["Anime", "Romance", "Fantasy", "Drama"],
    director: "Makoto Shinkai",
    actors: ["Ryunosuke Kamiki", "Mone Kamishiraishi", "Ryo Narita"],
    language: "Japanese",
    year: 2016,
    rating: 8.4,
    runtime: 106,
    streaming: "Crunchyroll",
    description: "Two strangers find themselves linked in a bizarre way. When a connection is formed, will distance be the only thing to keep them apart?"
  },
  {
    id: "m20",
    title: "The Grand Budapest Hotel",
    genres: ["Comedy", "Drama", "Adventure"],
    director: "Wes Anderson",
    actors: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric"],
    language: "English",
    year: 2014,
    rating: 8.1,
    runtime: 99,
    streaming: "Hulu",
    description: "A writer relates his adventures at a renowned European resort hotel between the first and second World Wars."
  },
  {
    id: "m21",
    title: "Shutter Island",
    genres: ["Mystery", "Thriller"],
    director: "Martin Scorsese",
    actors: ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley"],
    language: "English",
    year: 2010,
    rating: 8.2,
    runtime: 138,
    streaming: "Paramount+",
    description: "Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient."
  },
  {
    id: "m22",
    title: "Arrival",
    genres: ["Sci-Fi", "Mystery", "Drama"],
    director: "Denis Villeneuve",
    actors: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    language: "English",
    year: 2016,
    rating: 7.9,
    runtime: 116,
    streaming: "Paramount+",
    description: "A linguist works with the military to communicate with alien lifeforces after twelve mysterious spacecraft appear around the world."
  },
  {
    id: "m23",
    title: "The Matrix",
    genres: ["Sci-Fi", "Action"],
    director: "Lana Wachowski",
    actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    language: "English",
    year: 1999,
    rating: 8.7,
    runtime: 136,
    streaming: "Max",
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence."
  },
  {
    id: "m24",
    title: "Roma",
    genres: ["Drama"],
    director: "Alfonso Cuarón",
    actors: ["Yalitza Aparicio", "Marina de Tavira", "Diego Cortina Autrey"],
    language: "Spanish",
    year: 2018,
    rating: 7.7,
    runtime: 135,
    streaming: "Netflix",
    description: "A year in the life of a middle-class family's maid in Mexico City in the early 1970s."
  },
  {
    id: "m25",
    title: "Mad Max: Fury Road",
    genres: ["Action", "Sci-Fi", "Adventure"],
    director: "George Miller",
    actors: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    language: "English",
    year: 2015,
    rating: 8.1,
    runtime: 120,
    streaming: "Max",
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max."
  }
];

module.exports = movieCatalog;
